dist: xenial
language: d
d:
  - dmd
  #- ldc

install: ./tools/download_llvm.d

before_script:
  - git fetch --unshallow
  - |
    if [ $TRAVIS_OS_NAME = 'osx' ]; then
      ./configure --llvm-path tmp/clang
    fi

script: dub test --verror --compiler=${DC}

os:
  - linux
  #- osx

env:
  global: MACOSX_DEPLOYMENT_TARGET=10.9
  jobs:
    - LLVM_VERSION=10.0.0
    #- LLVM_VERSION=9.0.0
    #- LLVM_VERSION=8.0.0 # used by Buildkite
    #- LLVM_VERSION=6.0.0 # Used by Sociomantic

jobs:
  include:
    # beta and nightly builds for DMD and LDC
    #- &entry
    #  d: dmd-beta
    #  os: linux
    #  env: LLVM_VERSION=10.0.0
    #- <<: *entry
    #  d: ldc-beta
    #- <<: *entry
    #  d: dmd-nightly

    # deployment
    - &deploy
      stage: deploy
      if: tag IS present
      d: dmd
      os: linux
      env: LLVM_VERSION=8.0.0
      install: ./tools/download_llvm.d --dstep
      before_script: ./configure --llvm-path tmp/clang
      script: ./tools/build_release.sh
      deploy:
        provider: releases
        token: $SECRET
        draft: true
        tag_name: $TRAVIS_TAG
        file_glob: true
        file: dstep*.tar.xz
        cleanup: true
        on:
          tags: true
    #- <<: *deploy
    #  os: osx
    #  before_install: brew install ncurses

  allow_failures:
    - <<: *entry
      d: dmd-nightly
